### ISSUE TITLE
Incorrect values returned for one-line functions that call other functions.

### ISSUE THREAD

**Issue by whitelynx** [stoeffel/retrieve-arguments#1]
The regexp used to match function arguments (currently `/function.*\((.*)\)/`) seems to be too greedy; if you pass a function that was defined on a single line, it can easily return incorrect results.
### Example:

``` javascript
function testFunc() { return something(this.somethingElse); }
retrieveArguments(testFunc);
```

Expected result:

``` javascript
[]
```

Actual result:

``` javascript
[ 'this.somethingElse' ]
```

This can be fixed by making the regexp more selective:

``` javascript
/function[^(]*\(([^)]*)\)/
```

**Comment by stoeffel** [comment]
looks good. can you make a PR?

**Comment by whitelynx** [comment]
Sure, will do.
